{
  "result": true,
  "product_data": [
    {
      "pro_id": 1,
      "catalog_no": "12311708",
      "catalog_desc": "TY 100*80-12 MC69 GENX DS G-A 08",
      "style_no": "123117",
      "style_desc": "TY 100*80-12 MC69 GENX DS G-A",
      "pro_cat_id": "5400",
      "pro_cat_desc": "TYRES",
      "pro_sub_cat_id": "51805",
      "pro_sub_cat_desc": "MOTOR CYCLE TYRES",
      "brand": "5SRI",
      "brand_desc": "SRI - BICYCLE TYRES & TUBES",
      "block_for_sales": 0,
      "block_for_sales_return": 0,
      "block_for_invoice": 0,
      "catalog_short_desc": ""
    },
    {
      "pro_id": 2,
      "catalog_no": "12390121",
      "catalog_desc": "TY 90*100-10 MC69 GENX DS G- A 21",
      "style_no": "123901",
      "style_desc": "TY 90*100-10 MC69 GENX DS G- A",
      "pro_cat_id": "5400",
      "pro_cat_desc": "TYRES",
      "pro_sub_cat_id": "51805",
      "pro_sub_cat_desc": "MOTOR CYCLE TYRES",
      "brand": "5SRI",
      "brand_desc": "SRI - BICYCLE TYRES & TUBES",
      "block_for_sales": 0,
      "block_for_sales_return": 0,
      "block_for_invoice": 0,
      "catalog_short_desc": ""
    },
    {
      "pro_id": 3,
      "catalog_no": "GF013003",
      "catalog_desc": "BEAT GF0130-ASSTD 03",
      "style_no": "GF0130",
      "style_desc": "BEAT GF0130-ASSTD",
      "pro_cat_id": "5100",
      "pro_cat_desc": "FLIP FLOPS",
      "pro_sub_cat_id": "51008",
      "pro_sub_cat_desc": "WOMEN",
      "brand": "5SML",
      "brand_desc": "SML - FOOTWEAR",
      "block_for_sales": 0,
      "block_for_sales_return": 0,
      "block_for_invoice": 0,
      "catalog_short_desc": ""
    },
    {
      "pro_id": 4,
      "catalog_no": "GF013004",
      "catalog_desc": "BEAT GF0130-ASSTD 04",
      "style_no": "GF0130",
      "style_desc": "BEAT GF0130-ASSTD",
      "pro_cat_id": "5100",
      "pro_cat_desc": "FLIP FLOPS",
      "pro_sub_cat_id": "51008",
      "pro_sub_cat_desc": "WOMEN",
      "brand": "5SML",
      "brand_desc": "SML - FOOTWEAR",
      "block_for_sales": 0,
      "block_for_sales_return": 0,
      "block_for_invoice": 0,
      "catalog_short_desc": ""
    },
    {
      "pro_id": 5,
      "catalog_no": "GF013005",
      "catalog_desc": "BEAT GF0130-ASSTD 05",
      "style_no": "GF0130",
      "style_desc": "BEAT GF0130-ASSTD",
      "pro_cat_id": "5100",
      "pro_cat_desc": "FLIP FLOPS",
      "pro_sub_cat_id": "51008",
      "pro_sub_cat_desc": "WOMEN",
      "brand": "5SML",
      "brand_desc": "SML - FOOTWEAR",
      "block_for_sales": 0,
      "block_for_sales_return": 0,
      "block_for_invoice": 0,
      "catalog_short_desc": ""
    }
  ]
}
